name: Backend Dev CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'feat/dev-cd' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: .

      - name: Set up SSH config for jump server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.JUMP_SSH_KEY }}" > ~/.ssh/jump_key
          chmod 600 ~/.ssh/jump_key

          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/dev_key
          chmod 600 ~/.ssh/dev_key

          cat <<EOF > ~/.ssh/config
          Host dev-server
              HostName ${{ secrets.SSH_HOST }}
              User ubuntu
              IdentityFile ~/.ssh/dev_key
              ProxyJump jump-server

          Host jump-server
              HostName ${{ secrets.JUMP_SSH_HOST }}
              User ubuntu
              IdentityFile ~/.ssh/jump_key
          EOF

      - name: Copy JAR to dev server via jump server
        run: |
          scp -F ~/.ssh/config backend-jar/*.jar dev-server:/home/ubuntu/backend.jar

      - name: Restart backend via jump server
        run: |
          ssh -F ~/.ssh/config dev-server <<'EOS'
            pkill -f backend.jar || true
            nohup java -jar backend.jar > backend.log 2>&1 &
          EOS
