name: Release Backend JAR

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify tag is on main
        run: |
          TAG_COMMIT=$(git rev-parse HEAD)
          MAIN_COMMIT=$(git rev-parse origin/main)

          echo "🔖 Tag commit:  $TAG_COMMIT"
          echo "🌿 Main commit: $MAIN_COMMIT"

          if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
            echo "❌ Tag is not pointing to latest main commit. Aborting release."
            exit 1
          fi

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew bootJar -x test

      - name: Rename JAR
        run: cp build/libs/*.jar backend.jar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t luckyprice1103/onthetop-backend:${{ github.ref_name }} .
          docker push luckyprice1103/onthetop-backend:${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: backend.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
      
